from pptx import Presentation
from pptx.util import Pt
import os


def create_ppt(topic, slide_count):

    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])

    slide.shapes.title.text = topic
    slide.placeholders[1].text = "Generated by AbrarAI"

    # Content slides
    for i in range(1, slide_count):

        slide = prs.slides.add_slide(prs.slide_layouts[1])

        slide.shapes.title.text = f"{topic} - Part {i}"

        body = slide.placeholders[1]

        body.text = (
            f"Introduction to {topic}\n\n"
            f"• What is {topic}?\n"
            f"• Important concepts\n"
            f"• Main features\n"
            f"• Real-world applications\n"
            f"• Advantages and uses\n"
            f"• Key points to remember"
        )

        for paragraph in body.text_frame.paragraphs:
            paragraph.font.size = Pt(22)

    # Folder create
    os.makedirs("generated_ppts", exist_ok=True)

    filename = topic.lower().replace(" ", "_") + ".pptx"

    filepath = os.path.join(
        "generated_ppts",
        filename
    )

    prs.save(filepath)

    return filepath


if __name__ == "__main__":

    print("==============================")
    print("      ABRARAI PPT GENERATOR")
    print("==============================")

    topic = input("PPT kis topic par chahiye: ")

    slides = input("Kitne slides chahiye: ")

    try:
        slides = int(slides)
    except ValueError:
        slides = 10

    file = create_ppt(topic, slides)

    print()
    print("✅ PPT successfully created!")
    print("📁 File:", file)